//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRailway
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRequest
    {
        public int id { get; set; }
        public string name { get; set; }
        public string CNIC { get; set; }
        public string email { get; set; }
    }
}
