//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRailway
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareRule
    {
        public int id { get; set; }
        public Nullable<int> trainNameID { get; set; }
        public Nullable<double> acFare { get; set; }
        public Nullable<double> sleeperFare { get; set; }
        public Nullable<double> economyFare { get; set; }
    
        public virtual TrainName TrainName { get; set; }
    }
}
